# Generated by Django 5.2.10 on 2026-08-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_discussionroom_discussionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmessage',
            name='parent_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_rooms', to='core.discussionmessage'),
        ),
    ]
