# Generated by Django 5.2.10 on 2026-08-05 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_discussionmessage_parent_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionmessage',
            name='parent_room',
        ),
        migrations.AddField(
            model_name='discussionroom',
            name='parent_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_rooms', to='core.discussionroom'),
        ),
    ]
