# Generated by Django 5.2.16 on 2026-08-16 16:03

import cloudinary_storage.storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(storage=core.models.NoteCloudinaryStorage(), upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profiles/'),
        ),
    ]
