# Generated by Django 5.2.16 on 2026-09-03 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('note_created', 'Note Created'), ('new_note', 'New Note'), ('note_updated', 'Note Updated'), ('note_deleted', 'Note Deleted'), ('blog_created', 'Blog Created'), ('new_blog', 'New Blog'), ('blog_updated', 'Blog Updated'), ('blog_deleted', 'Blog Deleted'), ('room_created', 'Room Created'), ('new_room', 'New Room'), ('room_joined', 'Room Joined'), ('room_left', 'Room Left'), ('room_message', 'Room Message'), ('system', 'System')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=180),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='core_notifi_recipie_1d5476_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='core_notifi_recipie_4d7e73_idx'),
        ),
    ]
