# Generated by Django 5.2.16 on 2026-09-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification_actor_notification_read_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('note_created', 'Note Created'), ('new_note', 'New Note'), ('note_updated', 'Note Updated'), ('note_deleted', 'Note Deleted'), ('note_download', 'Note Downloaded'), ('blog_created', 'Blog Created'), ('new_blog', 'New Blog'), ('blog_updated', 'Blog Updated'), ('blog_deleted', 'Blog Deleted'), ('room_created', 'Room Created'), ('new_room', 'New Room'), ('room_joined', 'Room Joined'), ('room_left', 'Room Left'), ('room_message', 'Room Message'), ('system', 'System')], max_length=40),
        ),
    ]
