# Generated by Django 5.2.16 on 2026-09-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='chapter',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='note',
            name='class_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='course',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='note',
            name='education_level',
            field=models.CharField(default='university', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='semester',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
